---
name: Mac-Pasteboard
version: 0.000_01
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Manipulate Mac OS X pasteboards
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 1.01
build_requires:
  ExtUtils::CBuilder: 0
dynamic_config: 1
provides:
  Mac::Pasteboard:
    file: lib/Mac/Pasteboard.pm
    version: 0.000_01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
